services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8086:8081"
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped

volumes:
  nexus-data:
    name: nexus-data
