---
- name: Deploy Jenkins and Gitea in containers
  hosts: localhost
  become: true
  tasks:
    - name: Install Docker
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: true

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull Jenkins
      docker_image:
        name: jenkins/jenkins:lts
        source: pull

    - name: Create Jenkins volume
      docker_volume:
        name: jenkins_home

    - name: Run Jenkins
      docker_container:
        name: jenkins
        image: jenkins/jenkins:lts
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - jenkins_home:/var/jenkins_home

    - name: Create directory for Gitea
      file:
        path: /opt/gitea
        state: directory
        mode: '0755'

    - name: Copy docker-compose.yml for Gitea
      copy:
        dest: /opt/gitea/docker-compose.yml
        content: |
          version: "3"
          networks:
            gitea:
              external: false
          services:
            server:
              image: gitea/gitea:1.22.3
              container_name: gitea
              environment:
                - USER_UID=1000
                - USER_GID=1000
              restart: always
              networks:
                - gitea
              volumes:
                - ./gitea:/data
                - /etc/timezone:/etc/timezone:ro
                - /etc/localtime:/etc/localtime:ro
              ports:
                - "3000:3000"
                - "2221:22"

    - name: Run Gitea with Docker Compose
      docker_compose:
        project_src: /opt/gitea
        state: present
  
  handlers:
    - name: Restart Gitea
      docker_compose:
        project_src: /opt/gitea
        state: restarted
    
    - name: Restart Jenkins
      docker_container:
        name: jenkins
        state: restarted