---
- name: Restart Grafana
  community.docker.docker_container:
    container_default_behavior: no_defaults 
    name: grafana
    state: started
    restart: true
  listen: restartContainerGrafana
...
